### ISSUE TITLE
Disabling premium features gives an error "Path to the script is not specified"

### ISSUE THREAD

**Issue by deep-space-explorer** [eroself/vaadin-litelement-ckeditor#63]
Disabling premium features gives an error "Path to the script is not specified".
Code below:

```
Config config = new Config();
List<Constants.Plugins> plugins = List.of(Constants.Plugins.ExportPdf, Constants.Plugins.ExportWord);//premium feature which needs a license
config.setRemovePlugins(plugins);


VaadinCKEditor classicEditor = new VaadinCKEditorBuilder().with(builder -> {
	builder.editorData = "This is a classic editor sample.";
	builder.editorType = Constants.EditorType.CLASSIC;
	builder.theme = Constants.ThemeType.DARK;
	builder.config = config;
}).createVaadinCKEditor();
```

error:
`Error: Path to the script is not specified.
at JS._validateSrc (VAADIN/build/generated-flow-imports-CYMl0Y6c.js:16562:1478)
at new JS (VAADIN/build/generated-flow-imports-CYMl0Y6c.js:16562:1276)
at yt._loadWscbundle (VAADIN/build/generated-flow-imports-CYMl0Y6c.js:16747:1923)
at yt.init (VAADIN/build/generated-flow-imports-CYMl0Y6c.js:16747:982)`

How to correctly disabe premium features?

With premium features turned on everyting works fine!

In application.properties I have:
`vaadin.allowed-packages=com.vaadin,org.vaadin,dev.hilla,com.wontlost`

**Comment by jet-pang** [comment]
Triaged against the current **5.3.0** codebase — closing as **not applicable** (archived 4.x API).

The `Config.setRemovePlugins(List.of(ExportPdf, ExportWord))` premium pattern no longer exists. On 5.3.0, premium features are **opt-in** rather than removed: they are only loaded if you explicitly add them via `addCustomPlugin(CustomPlugin.fromPremium("ExportPdf"))` and call `VaadinCKEditorPremium.enable()`. So to 'disable' premium you simply don't add them — there's no script-path error path anymore. See `VaadinCKEditorPremium.java`. Reopen against 5.3.0 if you still hit this. 🤖
